"""added type to Quest model

Revision ID: 58a50a5b9df8
Revises: aa51891b3ded
Create Date: 2024-10-27 11:27:40.032612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a50a5b9df8'
down_revision: Union[str, None] = 'aa51891b3ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'type')
    # ### end Alembic commands ###
