"""added mentor_comment

Revision ID: 40f521d4eea8
Revises: 58a50a5b9df8
Create Date: 2024-10-28 16:35:59.802075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f521d4eea8'
down_revision: Union[str, None] = '58a50a5b9df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_quest_progress', sa.Column('mentor_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_quest_progress', 'mentor_comment')
    # ### end Alembic commands ###
