name: Build and Deploy Containers to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.ACR_ACCESS_TOKEN }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ANY --password-stdin

    - name: Build FastAPI Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/fastapi:${{ github.sha }} -f path/to/fastapi/Dockerfile .
        docker tag ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/fastapi:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/fastapi:latest

    - name: Build PostgreSQL Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/postgres:${{ github.sha }} -f path/to/postgres/Dockerfile .
        docker tag ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/postgres:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/postgres:latest

    - name: Push FastAPI Docker image to ACR
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/fastapi:${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/fastapi:latest

    - name: Push PostgreSQL Docker image to ACR
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/postgres:${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/it_academy/postgres:latest
