on: [push]
name: CI/CD IT Academy app

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/it_academy:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/it_academy:latest

            
        # Step to navigate to the directory where Terraform files are located
        - name: Print working directory
          run: pwd

        - name: Change directory to Terraform folder
          run: cd ./infrastructure/stage

      # Initialize Terraform
        - name: Terraform Init
          run: terraform init

      # Apply Terraform configuration
        - name: Terraform Apply
          run: terraform apply -auto-approve



            
